export const tweets: string[] = [
  "Code like you’re explaining it to your future self.",
  "Every bug teaches you something new if you let it.",
  "Debugging is just you explaining your code to the computer until one of you understands.",
  "You’re not slow at coding; you’re just being precise.",
  "Writing clean code is an act of kindness to your future self.",
  "Learning never ends in tech—it only compounds.",
  "The best way to learn to code is to build something that breaks.",
  "It’s okay if your first project is ugly. The second one will be less ugly.",
  "A real developer doesn’t fear bugs—they fear not understanding them.",
  "Good code is like good writing: concise, readable, and honest.",
  "Every senior developer was once a beginner who didn’t quit.",
  "Deadlines come and go. Code lives forever.",
  "A comment should explain why, not what.",
  "The compiler isn’t angry at you—it’s just brutally honest.",
  "Simplicity is not easy; it’s the highest form of mastery.",
  "Coding isn’t about typing fast; it’s about thinking deeply.",
  "Frameworks change. Fundamentals stay.",
  "Learn to read error messages; they’re your best teachers.",
  "Most coding problems are communication problems in disguise.",
  "Sometimes, deleting code is the most productive thing you can do.",
  "You don’t need to know everything—you just need to know how to find it.",
  "Programming is 10% writing code and 90% figuring out why it doesn’t work.",
  "Small consistent improvements beat random bursts of productivity.",
  "You can’t rush craftsmanship.",
  "You don’t master coding; you just get better at being wrong.",
  "Works on my machine is not a success metric.",
  "A commit a day keeps the anxiety away.",
  "Refactoring is like cleaning your room—you’ll thank yourself later.",
  "Never copy-paste without understanding what it does.",
  "Your first draft of code should never be your last.",
  "Curiosity is a developer’s superpower.",
  "Great developers aren’t born; they’re debugged.",
  "Code that is hard to read is code that will break later.",
  "If you’re stuck, step away. Your brain debugs better offline.",
  "Learn one new tool, not ten halfways.",
  "Documentation is part of the product, not an afterthought.",
  "Every broken feature is an opportunity to learn how systems fail.",
  "Good naming is half the design.",
  "Don’t optimize early—optimize clarity.",
  "The best code review is a conversation, not a correction.",
  "Programming is the art of controlled confusion.",
  "If your code needs a comment to explain it, maybe rewrite it.",
  "Don’t chase trends; chase understanding.",
  "Great developers build habits, not hacks.",
  "Your codebase is a garden—prune it often.",
  "Don’t fear legacy code. Fear ignorance of why it works.",
  "Learning to read code is more important than writing it.",
  "If you think something is obvious, document it anyway.",
  "Building software is 20% code, 80% empathy.",
  "Good code doesn’t need to shout—it speaks clearly.",
  "You can’t Google intuition. You earn it through experience.",
  "A bug is just a puzzle that hasn’t been solved yet.",
  "The first step to fixing bad code is admitting it’s yours.",
  "Programming teaches patience more than any meditation app.",
  "Don’t compare your chapter 1 to someone else’s chapter 10.",
  "One good pull request is better than ten unfinished ideas.",
  "If your app runs, be grateful. If it runs well, be proud.",
  "Tech will change; problem-solving won’t.",
  "Perfection is the enemy of shipping.",
  "Every language teaches you a new way to think.",
  "Errors are feedback, not failure.",
  "Automate what you hate.",
  "Learn version control before you wish you did.",
  "Consistency in naming is free readability.",
  "Software doesn’t get finished; it gets maintained.",
  "Your brain is not RAM—write things down.",
  "Good design feels inevitable in hindsight.",
  "Don’t chase productivity tools; chase consistency.",
  "The best code is no code—if you can delete it, do it.",
  "Read code from open source—it’s free mentorship.",
  "Learn enough to be dangerous, then go break things safely.",
  "Hard problems are just unsolved easy ones.",
  "Never deploy on Friday unless you love chaos.",
  "everything matters", 
  "Write tests for future you, not past you.",
  "Time spent naming variables is never wasted.",
  "Your side project might be your portfolio tomorrow.",
  "The fastest code is the code you didn’t have to run.",
  "Design your APIs like you design your conversations.",
  "Don’t just learn syntax, learn systems.",
  "Every experienced developer once broke production.",
  "Good developers automate; great developers simplify.",
  "Your first bug fix is your real Hello World.",
  "Code that surprises you later was probably unclear today.",
  "Learn to build before you learn to scale.",
  "Good UI hides complexity; good code manages it.",
  "If it’s hard to test, it’s probably hard to maintain.",
  "Tech debt is a loan; pay the interest early.",
  "Don’t just solve problems—understand why they exist.",
  "Every tool is good until it’s overused.",
  "Great teams ship boring code that works.",
  "The best documentation is one you actually update.",
  "Comments rot faster than code—keep them honest.",
  "Junior devs fear breaking things. Seniors fear not learning.",
  "It’s okay if you don’t understand something right away.",
  "The more you learn, the more you realize how much you don’t know.",
  "Chasing perfection is the fastest way to burnout.",
  "Every project starts with chaos and ends with pride.",
  "Complexity grows naturally—simplicity takes effort.",
  "You don’t need a new library; you need clarity.",
  "Your codebase is a living organism. Treat it with care.",
  "Take breaks. Your code benefits from oxygen.",
  "The best developers are curious, not just skilled.",
  "You’re only one bug away from understanding everything.",
  "Write code that reads like a story, not a riddle.",
  "Future you is your most important collaborator.",
  "Done is better than perfect when perfect never comes.",
  "Bugs don’t mean failure; they mean feedback.",
  "Don’t fear reviews. Fear silence.",
  "Every project is a new beginning, not a new burden.",
  "The most productive developers are the calmest ones.",
  "Your job isn’t to write code; it’s to solve problems.",
  "A clean UI starts with clean logic.",
  "Never stop asking why—especially when it works.",
  "The most beautiful code disappears into the product.",
  "Good engineers automate; great ones document why.", 
  "Nothing matters."
];

